### ISSUE TITLE
Corrupted Notebooks / Missing imports

### ISSUE THREAD

**Issue by straussmaximilian** [automl/TransformersCanDoBayesianInference#1]
Hi,

Thank you for making your code available. I wanted to explore the notebooks and rerun the code. However, I did run into a couple of issues:

When opening `BayesianModels_And_Custom_Pyro_Modules.ipynb`, there is an error: [The Notebook Does Not Appear to Be Valid JSON](https://github.com/automl/TransformersCanDoBayesianInference/blob/master/notebooks/BayesianModels_And_Custom_Pyro_Modules.ipynb). 
When cloning the repo and opening locally, it says it is an unreadable notebook.
<img width="713" alt="Screen Shot 2022-01-29 at 8 09 59 PM" src="https://user-images.githubusercontent.com/16521288/151674511-474be6a7-98a7-496f-a555-bcdcceef4b5c.png">
It looks like this notebook is corrupted.

The `requirements.txt` seems incomplete, and a couple of imports needed for the notebooks seem to be missing (e.g. `samlib`, `botorch`, `pytorch_tabnet`). It would be great to see which packages were used to generate the results. I tried installing samlib via pip, but this seems to be a different package and has not the `.utils`

When running `TabularEvalSimple`, there is an import error as train cannot be found - the other notebooks have the sys path append at the beginning - so maybe this is missing. I added it and can run until `Loading PFN` - this fails with a `FileNotFoundError` as `results/tabular_model_bnn.ckpt` is not found.

Any help with running the notebooks would be appreciated. Thanks.

**Comment by noahho** [comment]
Hi Maximilian,

Thanks a lot for your interest in our work! We're sorry that the code didn't work out of the box. I will update the notebooks in this or the coming week, I think this will be the easiest fix for now - I'll make a comment in here as soon as this is done.

One issue I can quickly help with. The mentioned packages samlib, botorch, pytorch_tabnet are not necessary to run our experiments, so you will get away with removing these imports.

Best
Noah

**Comment by noahho** [comment]
I went through the notebooks and checked that they ran for me - I hope it does for you too. Among other problems some files were corrupted during upload. Thanks a lot for making us aware!

**Comment by SamuelGabriel** [comment]
I went through the notebooks another time in another environment, where it works as well now. I think you should not run into any more problems like the above. Closing this. Please, open again, if I am not right. :)
